spring:
  datasource:
    url: jdbc:mysql://192.168.0.81:3306/sfg_prod
    password: lee
    username: sfg_prod_user
    platform: mysql
  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
# properties:
#      javax:
#       persistence:
#         schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#*/
  profiles: prod
    